name: Build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Code Formatting
        run: mvn spring-javaformat:apply

      - name: Maven Build
        run: mvn --batch-mode clean package -DskipTests
